# The .bashrc and .bash_profile files must remain in our home directory (~ or /c/Users/<username> if using Windows). 
# This is because these are the specific locations where Bash looks for these files by default during startup, and this behavior is not configurable without modifying the Bash source code.

if [ -f ~/.bash/@shell/main ]; then
    source ~/.bash/@shell/main
fi