#!/bin/bash
# The .bashrc and .bash_profile files must remain in our home directory (~ or /c/Users/<username> if using Windows).
# This is because these are the specific locations where Bash looks for these files by default during startup, and this behavior is not configurable without modifying the Bash source code.

# shellcheck source=/dev/null
if [ -f ~/.bash/@init/shell-init.sh ]; then
    source ~/.bash/@init/shell-init.sh
fi
